list_of_variable = [
    "UCI.Loop[?].Setpoints.ActivePowerReference.Source_Out",
    "UCI.Loop[?].Setpoints.ActivePowerReference.Reference_Out",
    "UCI.Loop[?].DataHandler.ActivePowerRef[0].Reference_In",
    "UCI.Loop[?].DataHandler.ActivePowerRef[1].Reference_In",
    "UCI.Loop[?].DataHandler.ActivePowerRef[1].Activation_In",
    "UCI.Loop[?].Setpoints.ReactivePowerReference.Source_Out",
    "UCI.Loop[?].Setpoints.ReactivePowerReference.Reference_Out",
    "UCI.Loop[?].DataHandler.ReactivePowerRef[0].Reference_In",
    "UCI.Loop[?].DataHandler.ReactivePowerRef[1].Reference_In",
    "UCI.Loop[?].DataHandler.ReactivePowerRef[1].Activation_In",
    "UCI.Loop[?].Setpoints.VoltageReference.Source_Out",
    "UCI.Loop[?].Setpoints.VoltageReference.Reference_Out",
    "UCI.Loop[?].DataHandler.VoltageRef[0].Reference_In",
    "UCI.Loop[?].DataHandler.VoltageRef[1].Reference_In",
    "UCI.Loop[?].DataHandler.VoltageRef[1].Activation_In",
    "UCI.Loop[?].Setpoints.PowerFactorReference.Source_Out",
    "UCI.Loop[?].Setpoints.PowerFactorReference.Reference_Out * 1000",
    "UCI.Loop[?].DataHandler.PowerFactorRef[0].Reference_In * 1000",
    "UCI.Loop[?].DataHandler.PowerFactorRef[1].Reference_In * 1000",
    "UCI.Loop[?].DataHandler.PowerFactorRef[1].Activation_In",
    "UCI.Loop[?].DataHandler.ActivePowerShutdown.Shutdown_In",
    "UserDataAccess.VoltageSlopeCtrlLoop[?].Configuration.ReactivePwrOffset_kVAR"
    ]